### PR TITLE
Trim travis config, now that other dists than trusty are supported.

### PR DESCRIPTION
**Pull request by simpoir**

### CODE REVIEW

**Comment by maxiberta** [comment]
Nice cleanup \o/ ! Some jobs are failing with missing deps, though.

**Comment by simpoir** [comment]
I know. I thought "draft" would mean to not notify reviewers but still run tests…

**Comment by simpoir** [comment]
Reopen, to retrigger travis.

**Review by maxiberta — APPROVED** [review]
LGTM!

**Pull request merged**
